<?php

/**
 * @file
 * Core functions for the Field tokens module.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldItemInterface;

/**
 * Implements hook_custom_formatters_token_data_alter().
 */
function field_tokens_custom_formatters_token_data_alter(array &$token_data, array $context): void {
  $item = $context['item'];
  if (!$item instanceof FieldItemInterface) {
    return;
  }

  $field_definition = $item->getFieldDefinition();
  $field_type = $field_definition->getType();
  $entity = $item->getEntity();

  $token_data['formatted_field-' . $field_type] = [$item];
  $token_data['_field_tokens_items'] = [$item];
  $token_data['entity'] = $entity;
  $token_data['entity_type'] = $entity->getEntityTypeId();
  $token_data['field'] = $field_definition;
  $token_data['field_name'] = $entity->getEntityTypeId() . '-' . $field_definition->getName();
  $token_data[$token_data['field_name']] = [$item];
}
